language: objective-c

rvm: 
  - 2.2.4

before_install:
  - gem install cocoapods -v '0.39.0'

branches:
  only:
    master

env: export LANG=en_US.UTF-8

script: bin/test

notifications:
  email:
    on_failure: change
